name: Upload Website
on:
  push:
    branches: ["main", "staging"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Website
        uses: big-help-ai/deploy-react@main
        with:
          organization: big-help-ai
          gh-token: ${{ secrets.GH_PAT }}
          s3-prefix: ${{ github.ref == 'refs/heads/main' && 'friendforce-react' || 'friendforce-react-staging' }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-bucket: "cdn.bighelp.ai"
          build-env: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
